server:
  port: 8080

spring:
  profiles:
    default: dev

  sql:
    init:
      platform: mysql

  datasource:
    url: jdbc:mysql://localhost:3306/root # 변경해주세요
    username: root # Database ID
    password: 1234 # Database Password
    driver-class-name: com.mysql.cj.jdbc.Driver

---
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: test

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa # Database ID
    password:  # Database Password
    driver-class-name: org.h2.Driver

#spring:
#  h2:
#    console:
#      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
#      path: /h2-console  # H2 Console의 Path
#  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
#  datasource:
#    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
#    url: jdbc:h2:~/test  # H2 접속 정보
#    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
#    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)